; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

//可能需要外部传入的变量，定义缺省值
#ifndef PreDefine_AppVersion
//外部命令行执行，把版本号传递进来 ISCC.exe Example1.iss /DPreDefine_AppVersion=1.2.3.4
#define PreDefine_AppVersion      "1.0.3"
#endif


#define Define_AppPublisher       "Revopoint"
#define Define_CompanyName        "Revopoint 3D Technologies Inc."
#define Define_CompanyURL         "https://www.revopoint3d.com/"

//一般不变的常量、字串定义
#define Define_AppId              "{{DFF310A3-37A5-3CB3-0283-9CE6E1B7F730}}"
#define Define_AppName            "Revo Mirror"
#define Define_MainExeName        "RevoMirror.exe"
//*** 用于查找窗口，判定程序是否正在运行中	
#define Define_AppWindowName      "Revo Mirror"

//Innosetup script & resource
#define MyResourceDir             	".\res"
#define MyLanguageDir               ".\res\language"
#define MyCoreDir				  	        ".\res\core"
#define MyTmpDir                  	".\res\tmp"
#define MySetupIconFile           	".\res\core\setup_icon.ico"

//程序文件（文件夹的所有子内容）输入，安装包输出到指定路径，根据需要更改
;#define MyAppDir                  	"..\..\..\build\bin"
#define MyAppDir                  	"..\..\..\build\cpack_artifacts\_CPack_Packages\win64\INNOSETUP\RevoMirror"
#define MyRuntimeLib                ".\runtime_lib"             
#define MyOutputDir               	".\setup"
#define MyOutputSetupFileName     	"RevoMirror-"+PreDefine_AppVersion+"-windows-x86_64"

//目前仅编译支持64位的程序安装包
#define x64BuildOnly
;#undef x64BuildOnly


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#Define_AppId}
AppName={#Define_AppName}

AppVersion={#PreDefine_AppVersion}
AppVerName={#Define_AppName} v{#PreDefine_AppVersion}
AppPublisher={#Define_AppPublisher}
AppPublisherURL={#Define_CompanyURL}
AppSupportURL={#Define_CompanyURL}
AppUpdatesURL={#Define_CompanyURL}
OutputDir={#MyOutputDir}
OutputBaseFilename={#MyOutputSetupFileName}
SetupIconFile={#MySetupIconFile}
UninstallDisplayIcon={app}\{#Define_MainExeName}
DisableProgramGroupPage=yes
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ShowLanguageDialog = yes
LanguageDetectionMethod = locale
//目前指定安装目标Windows版本为Win10以上
MinVersion = 10.0


#ifdef x64BuildOnly
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={commonpf64}\{#Define_AppName}
#else
ArchitecturesAllowed=x86 x64
DefaultDirName={commonpf32}\{#Define_AppName}
#endif



[Languages]
Name: "english"; MessagesFile: "{#MyLanguageDir}\English.isl"; 
Name: "chinesesimplified"; MessagesFile: "{#MyLanguageDir}\ChineseSimplified.isl";


[Tasks]
//默认创建桌面图标
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "{#MyAppDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyRuntimeLib}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyTmpDir}\*"; DestDir: "{tmp}"; Flags: ignoreversion dontcopy recursesubdirs createallsubdirs solidbreak nocompression; Attribs: hidden system
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#Define_AppName}"; Filename: "{app}\{#Define_MainExeName}"
Name: "{autodesktop}\{#Define_AppName}"; Filename: "{app}\{#Define_MainExeName}"; Tasks: desktopicon

[Run]
; 按顺序执行各种配置脚本
Filename: "icacls"; Parameters: """{app}"" /reset"; Flags: runhidden waituntilterminated
Filename: "{app}\scripts\update-path.bat"; Parameters: "add"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated
Filename: "{app}\scripts\add-firewall-rule.bat"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated
Filename: "{app}\scripts\install-service.bat"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated

[UninstallRun]
; 按顺序执行卸载脚本
Filename: "{app}\scripts\delete-firewall-rule.bat"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated
Filename: "{app}\scripts\uninstall-service.bat"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated  
; Filename: "{app}\sunshine.exe"; Parameters: "--restore-nvprefs-undo"; WorkingDir: "{app}"; Flags: runhidden waituntilterminated
Filename: "{app}\scripts\update-path.bat"; Parameters: "remove"; WorkingDir: "{app}\scripts"; Flags: runhidden waituntilterminated

[Registry]
Root: HKLM; Subkey: "SOFTWARE\{#Define_AppPublisher}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "SOFTWARE\{#Define_AppPublisher}\{#Define_AppName}"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\{#Define_AppPublisher}\{#Define_AppName}"; ValueType: string; ValueName: "Version"; ValueData: "{#PreDefine_AppVersion}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\{#Define_AppPublisher}\{#Define_AppName}"; ValueType: string; ValueName: "ExecuteName"; ValueData: "{#Define_MainExeName}"; Flags: uninsdeletekey




[Code]
#include MyCoreDir + "\coreScript.iss"
